import{i as a,S as p}from"./assets/vendor-CfzARMK3.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const f=document.querySelectorAll(".marquee");f.forEach(t=>{t.innerHTML+=t.innerHTML});const m=document.querySelector(".reviews-list-js"),l=document.querySelector(".reviews-placeholder-js"),u=document.querySelector(".prev-btn-js"),d=document.querySelector(".next-btn-js"),h="https://portfolio-js.b.goit.study/api/reviews";fetch(h).then(t=>{if(!t.ok)throw new Error("Failed to load reviews");return t.json()}).then(t=>{if(!t.length){l.classList.remove("visually-hidden");return}const o=t.map(({avatar_url:s,author:i,review:e})=>`
        <li class="swiper-slide review-item">
          <p class="review-text">${e}</p>
          <div class="author-info">
          <img class="author-img" src=${s} alt="${i}"
          <p style="bold" class="reviewer-name">${i}</p>
          </div>
        </li>`).join("");m.innerHTML=o,y()}).catch(()=>{a.error({message:"Failed to load reviews",position:"topRight"}),l.classList.remove("visually-hidden")});function y(){new p(".reviews-slider-js",{slidesPerView:1,spaceBetween:16,loop:!1,autoHeight:!0,navigation:{prevEl:".prev-btn-js",nextEl:".next-btn-js"},keyboard:{enabled:!0},on:{reachBeginning(){u.disabled=!0},fromEdge(){u.disabled=!1,d.disabled=!1},reachEnd(){d.disabled=!0}}})}const c=document.querySelector("#contactForm");c.addEventListener("submit",async t=>{t.preventDefault();const o=new FormData(c);try{if(!(await fetch("https://portfolio-js.b.goit.study/api/requests",{method:"POST",body:o})).ok)throw new Error("Something went wrong when submitting the application.");a.success({title:"Thank you for your interest in cooperation!",message:"The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch.",position:"center"}),c.reset()}catch(s){a.error({title:"Помилка",message:s.message||"An error occurred. Try again!",position:"center"})}});
//# sourceMappingURL=index.js.map
